### PR TITLE
Added film view elements: commenting functionality, checking film wat…

### PR DESCRIPTION
**Pull request by kreban**
…ched, scheduling film; removed CommentModel; might break things!

### CODE REVIEW

**Review by AurisP — CHANGES_REQUESTED** [review]
Removing CommentModel breaks alot of code and database changes would be needed. Needs to be worked on outside of master branch if this change to commenting is deemed necessary

**Comment by mihkelaaremae** [comment]
Just gonna drop by and recommend amending commits in the future if you ever need to "Fix a typo" or "Resolve merge conflicts". You'll also need to force push after that but the history will look much neater in the long run.

**Review by AurisP — APPROVED** [review]
The UI elements are added now without breaking the commenting

**Review by mihkelaaremae — DISMISSED** [review]
Perhaps get rid of search button, as the app now searches as we type?

**Pull request merged**
